import React from 'react';
import StatusBadge from './StatusBadge';

/**
 * AiAnalysisCard displays the decomposition generated by analyzeTask().
 * Displays strictly existing fields: category, required_skills, priority, difficulty, summary.
 */
export default function AiAnalysisCard({
  analysis,
  onProceed,
  onEdit,
  isProceeding = false
}) {
  if (!analysis) return null;

  const {
    category = 'General',
    required_skills = [],
    priority = 'Medium',
    difficulty = 3,
    summary = ''
  } = analysis;

  return (
    <div className="bg-gradient-to-br from-emerald-50/70 via-teal-50/40 to-white border-2 border-emerald-500/40 rounded-3xl p-6 shadow-md space-y-5 animate-in fade-in duration-200">
      {/* Card Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-emerald-100 pb-4">
        <div className="flex items-center space-x-2.5">
          <div className="w-9 h-9 rounded-xl bg-emerald-600 text-white flex items-center justify-center font-bold text-lg shadow-sm shadow-emerald-600/30">
            ⚡
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[11px] font-bold text-emerald-800 uppercase tracking-wider bg-emerald-100/80 px-2 py-0.5 rounded-full">
                AI Task Decomposition
              </span>
              <span className="text-xs text-slate-400">•</span>
              <span className="text-xs font-semibold text-slate-600">Extracted Requirements</span>
            </div>
            <h3 className="text-base sm:text-lg font-bold text-slate-900 mt-0.5">
              Task Analysis & Skill Mapping
            </h3>
          </div>
        </div>

        {/* Priority & Category Badges */}
        <div className="flex items-center space-x-2">
          <span className="text-xs font-bold px-2.5 py-1 rounded-lg bg-white border border-emerald-200 text-emerald-800 shadow-2xs">
            {category}
          </span>
          <StatusBadge type={priority} size="sm" showDot={true} />
        </div>
      </div>

      {/* Task Summary (if extracted) */}
      {summary && (
        <div className="bg-white/80 p-3.5 rounded-2xl border border-emerald-100/80 text-xs text-slate-700 space-y-1">
          <div className="font-bold text-slate-900 flex items-center gap-1.5">
            <span>📝</span>
            <span>Task Objective:</span>
          </div>
          <p className="text-slate-600 leading-relaxed italic">
            "{summary}"
          </p>
        </div>
      )}

      {/* Grid of Key Attributes */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {/* Required Skills */}
        <div className="bg-white/90 p-4 rounded-2xl border border-emerald-100 shadow-2xs space-y-2">
          <div className="flex justify-between items-center">
            <span className="text-xs font-bold text-slate-700 uppercase tracking-wider">
              Identified Skills ({required_skills.length})
            </span>
            <span className="text-[10px] text-emerald-700 font-semibold bg-emerald-50 px-2 py-0.5 rounded-full">
              60% Weight Factor
            </span>
          </div>
          <div className="flex flex-wrap gap-1.5 pt-1">
            {required_skills.length > 0 ? (
              required_skills.map((skill, idx) => (
                <span
                  key={idx}
                  className="text-xs px-2.5 py-1 bg-emerald-100/70 text-emerald-900 font-semibold rounded-lg border border-emerald-200/60 shadow-2xs flex items-center gap-1"
                >
                  <span className="text-emerald-600">✓</span>
                  <span>{skill}</span>
                </span>
              ))
            ) : (
              <span className="text-xs text-slate-400 italic">No specific skill keywords isolated</span>
            )}
          </div>
        </div>

        {/* Difficulty & Complexity */}
        <div className="bg-white/90 p-4 rounded-2xl border border-emerald-100 shadow-2xs space-y-2">
          <div className="flex justify-between items-center">
            <span className="text-xs font-bold text-slate-700 uppercase tracking-wider">
              Task Complexity
            </span>
            <span className="text-xs font-bold text-amber-600">Level {difficulty} / 5</span>
          </div>

          <div className="flex items-center space-x-1.5 pt-1">
            {Array.from({ length: 5 }).map((_, i) => (
              <div
                key={i}
                className={`h-2 flex-1 rounded-full transition-all ${
                  i < difficulty ? 'bg-amber-500' : 'bg-slate-200'
                }`}
              />
            ))}
          </div>

          <div className="text-[11px] text-slate-500 pt-1">
            {difficulty <= 2 && 'Low complexity — suitable for junior or busy team members.'}
            {difficulty === 3 && 'Moderate complexity — balanced skill proficiency recommended.'}
            {difficulty >= 4 && 'High complexity — requires senior proficiency in primary skills.'}
          </div>
        </div>
      </div>

      {/* Transparency explainer */}
      <div className="text-[11px] text-slate-500 bg-white/60 p-3 rounded-xl border border-emerald-100/60 flex items-start gap-2">
        <span className="text-emerald-600 font-bold shrink-0">ℹ️</span>
        <span>
          The recommendation engine will now match these <strong>{required_skills.length} skills</strong> against our employee profiles, weighting skills proficiency (60%), past performance (25%), and availability (15%).
        </span>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row items-center justify-end gap-3 pt-2">
        {onEdit && (
          <button
            type="button"
            onClick={onEdit}
            disabled={isProceeding}
            className="w-full sm:w-auto px-4 py-2.5 text-xs font-semibold text-slate-700 hover:text-slate-900 bg-white border border-slate-300 rounded-xl hover:bg-slate-50 transition-colors disabled:opacity-50"
          >
            ← Revise Description
          </button>
        )}

        {onProceed && (
          <button
            type="button"
            onClick={onProceed}
            disabled={isProceeding}
            className="w-full sm:w-auto px-6 py-2.5 text-xs sm:text-sm font-bold text-white bg-emerald-600 hover:bg-emerald-700 rounded-xl shadow-md shadow-emerald-600/25 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
          >
            {isProceeding ? (
              <>
                <span className="animate-spin text-sm">🔄</span>
                <span>Calculating Match Scores...</span>
              </>
            ) : (
              <>
                <span>Get Recommendation</span>
                <span>→</span>
              </>
            )}
          </button>
        )}
      </div>
    </div>
  );
}
